/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InferfazUsuario;

import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import objetosNegocio.Consulta;
import objetosNegocio.Orden;
import objetosNegocio.Servicio;

/**
 *
 * @author duzk
 */
public class DlgConsultasPaciente extends javax.swing.JDialog {

    private ArrayList<Consulta> consultas;
    
    /**
     * Creates new form DlgConsultasPaciente
     */
    public DlgConsultasPaciente(java.awt.Frame parent, boolean modal,ArrayList<Consulta> consultas) {
        super(parent, modal);

        initComponents();
        this.consultas = consultas;
        this.inicializarDatos();
        
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        textoDireccion = new javax.swing.JTextField();
        textoNSS = new javax.swing.JTextField();
        textoTelefono = new javax.swing.JTextField();
        consultasComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoConsulta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nombre del Paciente:");

        jLabel2.setText("NSS:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Telefóno:");

        consultasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        consultasComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                consultasComboBoxItemStateChanged(evt);
            }
        });
        consultasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Consultas:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/figura-de-usuario.png"))); // NOI18N

        textoConsulta.setColumns(20);
        textoConsulta.setRows(5);
        jScrollPane1.setViewportView(textoConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoNSS, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(consultasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(331, 331, 331))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textoNSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      
    }//GEN-LAST:event_formWindowClosed

    private void consultasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasComboBoxActionPerformed
        inicializaTextoConsulta();

    }//GEN-LAST:event_consultasComboBoxActionPerformed

    private void consultasComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_consultasComboBoxItemStateChanged
        inicializaTextoConsulta();
        
    }//GEN-LAST:event_consultasComboBoxItemStateChanged


    public void inicializaTextoConsulta(){
        Consulta consulta = (Consulta) consultasComboBox.getSelectedItem();
        int numeroConsulta = consulta.getNumeroConsulta();

        String diagnostico = consulta.getReceta().getDianostico();
        String tratamiento = consulta.getReceta().getTratamiento();
        
        String fechaReceta = String.valueOf(consulta.getReceta().getFecha().get(Calendar.DAY_OF_MONTH))+"/"
                +String.valueOf(consulta.getReceta().getFecha().get(Calendar.MONTH+1))+"/"
                +String.valueOf(consulta.getReceta().getFecha().get(Calendar.YEAR));
        
        int folioReceta = consulta.getReceta().getFolio();
        
        String ordenesConServicio = "";
        
        String receta = "Consulta Num: "+numeroConsulta+"\n"
                + "Folio: "+String.valueOf(folioReceta)+"\n"
                + "Fecha de Receta: "+fechaReceta+"\n"
                + "\n"
                + "Diagnóstico: "+diagnostico+"\n"
                + "\n"
                + "Tratamiento: "+tratamiento+"\n"
                + "\n";
        
        for (int i = 0; i < consulta.getListaOrdenes().size(); i++) {
            String numOrden = consulta.getListaOrdenes().get(i).getNumeroOrden();
            String nombreServicio = consulta.getListaOrdenes().get(i).getServicio();
            String nombreProveedor = consulta.getListaOrdenes().get(i).getNombreProovedor();
            String codigoProveedor = consulta.getListaOrdenes().get(i).getCodigoProovedor();
            String descripcionServicio = consulta.getListaServicios().get(i).getDescripcion();
            
            String separador = "--------------------------------------------------------------- \n";
            
            String ordenservicio = "Numero Orden: "+numOrden+"\n"
                    + "Nombre Servicio: "+nombreServicio+"\n"
                    + "Proveedor: "+nombreProveedor+" ID: "+codigoProveedor+"\n"
                    + "Descripción: \n"
                    + descripcionServicio+"\n"
                    + separador+"\n";
            ordenesConServicio = ordenesConServicio + (ordenservicio);
            System.out.println(ordenservicio);
        }
 
        
            
            
        String consultaCompleta = receta.concat(ordenesConServicio);
        
        textoConsulta.setText(consultaCompleta);
        
       
    }
    
    
    
    public void inicializarDatos(){
        
   
        
        textoNombre.setText(consultas.get(0).getPaciente().getNombre());
        textoDireccion.setText(consultas.get(0).getPaciente().getDireccion());
        textoNSS.setText(consultas.get(0).getPaciente().getNss());
        textoTelefono.setText(consultas.get(0).getPaciente().getTelefono());
        
        
       
        
        this.consultasComboBox.setModel(new DefaultComboBoxModel(consultas.toArray()));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> consultasComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textoConsulta;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoNSS;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables
}
